"""Roff (man page) renderer with cleaner sectioning and correct escapes."""
from __future__ import annotations
import datetime as _dt
import re
from .model import ModuleDoc
from .parsing import parse_doc_comment
from .sections import collect_module_sections, resolve_param_doc


def escape_roff(text: str) -> str:
    if not text:
        return ""
    text = text.replace("\\", r"\\")
    text = text.replace("-", r"\-")
    text = text.replace("'", r"\(aq")
    # Lines starting with '.' or "'" are roff control lines; escape them.
    if text.startswith(".") or text.startswith("'"):
        text = "\\&" + text
    return text


def _today() -> str:
    return _dt.date.today().isoformat()


def _render_doc_lines(doc_text: str, typedef_docs, struct_fields, *, label=None, fields=None):
    if not doc_text and not label and fields is None:
        return []
    info = parse_doc_comment(doc_text)
    out: list[str] = []

    if fields is not None:
        field_descs: dict[str, str] = {}
        for pn, pd in info.params.items():
            kind, inh = resolve_param_doc(pd, typedef_docs, struct_fields)
            if kind == "inherit":
                for line in inh:
                    m = re.match(r"\s*\.(\w+):?\s*(.*)", line)
                    if m:
                        field_descs[m.group(1)] = m.group(2).strip()
            else:
                field_descs[pn] = pd
        if info.description:
            out.append(".PP")
            for line in info.description.splitlines():
                out.append(escape_roff(line))
        if fields:
            out.extend([".PP", ".RS", ".nf"])
            mw = max(len(ft) for ft, _ in fields)
            any_d = any(fn in field_descs for _, fn in fields)
            nw = max((len(fn) + 1 for _, fn in fields if fn in field_descs), default=0)
            for ft, fn in fields:
                pad = ft.ljust(mw)
                fd = field_descs.get(fn, "")
                if fd and any_d:
                    out.append(f"{escape_roff(pad)} {escape_roff(fn + ':').ljust(nw)} {escape_roff(fd)}")
                else:
                    out.append(f"{escape_roff(pad)} {escape_roff(fn)}")
            out.extend([".fi", ".RE"])
        return out

    if label:
        out.append(f"\\fB{escape_roff(label)}:\\fR")
    if info.description:
        for line in info.description.splitlines():
            out.append(escape_roff(line))
    if info.params:
        out.append(".PP")
        out.append("\\fBParameters\\fR")
        for pn, pd in info.params.items():
            out.append(".RS")
            out.append(f"\\fI{escape_roff(pn)}\\fR")
            kind, inh = resolve_param_doc(pd, typedef_docs, struct_fields)
            if kind == "inherit":
                out.append(".RS")
                for line in inh:
                    m = re.match(r"\s*\.(\w+):?\s*(.*)", line)
                    if m:
                        out.append(f"\\fI.{escape_roff(m.group(1))}\\fR")
                        out.append(escape_roff(m.group(2)))
                    else:
                        out.append(escape_roff(line))
                out.append(".RE")
            else:
                out.append(escape_roff(pd))
            out.append(".RE")
    if info.returns:
        out.extend([".PP", "\\fBReturns\\fR", ".RS", escape_roff(info.returns), ".RE"])
    for title, items in [
        ("Preconditions", info.preconditions),
        ("Postconditions", info.postconditions),
        ("Invariants", info.invariants),
    ]:
        if items:
            out.extend([".PP", f"\\fB{title}\\fR"])
            for it in items:
                out.extend([".RS", escape_roff(it), ".RE"])
    return out


def _render_synopsis(comments):
    out = [".SH SYNOPSIS", ".nf"]
    for line in comments:
        if line.strip().startswith("```"):
            continue
        out.append(escape_roff(line))
    out.append(".fi")
    return out


def render_module_roff(doc: ModuleDoc) -> str:
    sec = collect_module_sections(doc)
    lines = [
        '.\\" Auto-generated by cflatdoc',
        f'.TH "{doc.module_name.upper()}" "3" "{_today()}" "Cflat" "{escape_roff(doc.title)}"',
        ".SH NAME",
        f"{escape_roff(doc.module_name)} \\- {escape_roff(doc.title)}",
    ]
    if doc.synopsis_comments:
        lines.extend(_render_synopsis(doc.synopsis_comments))
    lines.extend([".SH DESCRIPTION",
                  "Auto-generated API reference extracted from the public header."])

    if doc.declarations:
        lines.append(".SH FUNCTIONS")
        for fn, ret, params, decl, _nested in sec.parsed_decls:
            lines.append(".TP")
            if ret is not None and params is not None:
                lines.extend([".nf",
                              f"\\fB{escape_roff(fn)}\\fR",
                              f"{escape_roff(ret)} {escape_roff(fn)}({escape_roff(params)})",
                              ".fi"])
            else:
                lines.append(f"\\fB{escape_roff(fn)}\\fR")
            doc_text = doc.declaration_docs.get(decl, "") if decl else ""
            if doc_text:
                lines.extend(_render_doc_lines(doc_text, doc.typedef_docs, doc.struct_fields))

    if sec.all_type_names or doc.enums:
        lines.append(".SH TYPES")
        for type_name in sec.all_type_names:
            lines.extend([".TP", f"\\fB{escape_roff(type_name)}\\fR"])
            doc_text = doc.typedef_docs.get(type_name, "")
            fields = doc.struct_fields.get(type_name, [])
            lines.extend(_render_doc_lines(doc_text, doc.typedef_docs, doc.struct_fields,
                                            fields=fields or None))
        for enum in doc.enums:
            lines.extend([".TP", f"\\fB{escape_roff(enum.name)}\\fR : {escape_roff(enum.base_type)}"])
            if enum.doc:
                lines.append(".PP")
                for l in enum.doc.splitlines():
                    lines.append(escape_roff(l))
            if enum.members:
                lines.extend([".PP", ".RS", ".nf"])
                pairs = []
                for m in enum.members:
                    n = m.split("=", 1)[0].strip()
                    v = m.split("=", 1)[1].strip() if "=" in m else m
                    pairs.append((n, v))
                mw = max(len(n) for n, _ in pairs)
                for n, v in pairs:
                    lines.append(f"\\fB{escape_roff(n.ljust(mw))}\\fR  {escape_roff(v)}")
                lines.extend([".fi", ".RE"])

    for title, entries in [("OPTS", sec.opt_entries), ("SCOPES", sec.scope_entries),
                           ("FOREACH", sec.foreach_entries)]:
        if not entries:
            continue
        lines.append(f".SH {title}")
        for name, ret, params, nested in entries:
            lines.append(".TP")
            if ret is not None and params is not None:
                lines.extend([".nf", f"{escape_roff(ret)} {escape_roff(name)}({escape_roff(params)})", ".fi"])
            else:
                lines.append(f"\\fB{escape_roff(name)}\\fR")
            if nested:
                lines.extend([".RS", ".nf"])
                lines.extend(escape_roff(l) for l in nested)
                lines.extend([".fi", ".RE"])

    if sec.renderable_macros:
        lines.append(".SH MACROS")
        for macro in sec.renderable_macros:
            wrap = sec.resolved_macro_wrappers.get(macro)
            value = doc.macro_values.get(macro)
            rendered = macro
            if value:
                rendered = f"{macro} ({value})"
            if wrap:
                tgt, defaults = wrap
                dt = ", ".join(f"{k}={v}" for k, v in defaults.items()) if defaults else "none"
                rendered = f"{macro} : defaults {dt}; calls {tgt}(...)"
            lines.extend([".TP", f"\\fB{escape_roff(rendered)}\\fR"])
            d = doc.macro_docs.get(macro, "")
            if d:
                lines.append(".PP")
                for l in d.splitlines():
                    lines.append(escape_roff(l))

    lines.extend([".SH SEE ALSO", "\\fBcflat\\fR(3)"])
    return "\n".join(lines) + "\n"


def render_index_roff(modules, synopsis):
    lines = [
        '.\\" Auto-generated by cflatdoc',
        f'.TH "CFLAT" "3" "{_today()}" "Cflat" "Cflat library"',
        ".SH NAME",
        "cflat \\- Cflat API index",
    ]
    if synopsis:
        lines.extend(_render_synopsis(synopsis))
    lines.append(".SH MODULES")
    for m in modules:
        lines.extend([".TP", f"\\fB{escape_roff(m.module_name)}\\fR(3)", escape_roff(m.title)])
    return "\n".join(lines) + "\n"
